trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  proyecto: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.0.x'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: 'Publicar artefactos...'
      inputs:
        command: 'publish'
        projects: '$(proyecto)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'

    - task: AzureWebApp@1
      displayName: 'Desplegar en Azure App Service'
      inputs:
        azureSubscription: 'Azure subscription 1(762f4a76-192a-4a6e-af5b-ae87ab29bd90)'
        appName: 'PortafolioGustavoDelgado'
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
